function canMock() {
  return String(process.env.ALLOW_MOCK_PROVIDERS || 'false').toLowerCase() === 'true';
}

function base64(input) {
  return Buffer.from(input, 'utf8').toString('base64');
}

export async function createDocusignEnvelope({ lead, documentType, subject, message, templateId }) {
  const baseUrl = process.env.DOCUSIGN_BASE_URL || 'https://demo.docusign.net';
  const accountId = process.env.DOCUSIGN_ACCOUNT_ID;
  const accessToken = process.env.DOCUSIGN_ACCESS_TOKEN;

  if (!accountId || !accessToken) {
    if (canMock()) {
      return {
        provider: 'docusign_mock',
        providerRequestId: `mock_env_${Date.now()}`,
        status: 'sent',
        signingUrl: null,
        raw: { mocked: true, lead, documentType, templateId }
      };
    }
    throw new Error('DocuSign credentials are missing. Set DOCUSIGN_ACCOUNT_ID and DOCUSIGN_ACCESS_TOKEN.');
  }

  const signerName = lead.name || 'Client';
  const signerEmail = lead.email;
  if (!signerEmail) throw new Error('Lead email is required to create a DocuSign envelope');

  const body = templateId
    ? {
        templateId,
        templateRoles: [
          { email: signerEmail, name: signerName, roleName: 'Signer' }
        ],
        emailSubject: subject,
        emailBlurb: message,
        status: 'sent'
      }
    : {
        emailSubject: subject,
        emailBlurb: message,
        documents: [
          {
            documentBase64: base64(`
              <html>
                <body style="font-family: Arial, sans-serif; font-size: 14px; line-height: 1.5;">
                  <h1>${escapeHtml(subject || 'Real Estate Document')}</h1>
                  <p>This is a placeholder document generated by Real Estate AI Autopilot.</p>
                  <p><strong>Client:</strong> ${escapeHtml(signerName)}</p>
                  <p><strong>Document type:</strong> ${escapeHtml(documentType)}</p>
                  <p>Replace this placeholder with broker-approved templates before production use.</p>
                  <p style="margin-top: 80px;">Signature:</p>
                </body>
              </html>`),
            name: `${documentType || 'real_estate_document'}.html`,
            fileExtension: 'html',
            documentId: '1'
          }
        ],
        recipients: {
          signers: [
            {
              email: signerEmail,
              name: signerName,
              recipientId: '1',
              routingOrder: '1',
              tabs: {
                signHereTabs: [
                  { documentId: '1', pageNumber: '1', xPosition: '90', yPosition: '360' }
                ]
              }
            }
          ]
        },
        status: 'sent'
      };

  const response = await fetch(`${baseUrl}/restapi/v2.1/accounts/${accountId}/envelopes`, {
    method: 'POST',
    headers: {
      authorization: `Bearer ${accessToken}`,
      'content-type': 'application/json'
    },
    body: JSON.stringify(body)
  });

  const data = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new Error(`DocuSign envelope create failed: ${response.status} ${JSON.stringify(data)}`);
  }

  return {
    provider: 'docusign',
    providerRequestId: data.envelopeId || data.envelope_id || null,
    status: String(data.status || 'sent').toLowerCase(),
    signingUrl: null,
    raw: data
  };
}

export function parseDocusignWebhook(payload = {}) {
  const event = payload.event || payload.eventType || payload.status || 'unknown';
  const envelopeId = payload.data?.envelopeId || payload.envelopeId || payload.envelope_id || payload.data?.envelopeSummary?.envelopeId;
  const status = payload.data?.envelopeSummary?.status || payload.status || payload.data?.status || event;
  return { event, envelopeId, status, raw: payload };
}

function escapeHtml(value = '') {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}
